all:
	rm -f podcode.zip
	zip podcode.zip *.py *.txt
	cp podcode.zip /smb/eespjl/public_html/courses/CI/courseWork2010/
	rm -rf /smb/eespjl/public_html/courses/CI/courseWork2010/code/
	mkdir /smb/eespjl/public_html/courses/CI/courseWork2010/code/
	cp -r  *   /smb/eespjl/public_html/courses/CI/courseWork2010/code/

