/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainPanel.java
 *
 * Created on 15-Feb-2010, 16:32:11
 */

package redcode;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.StringReader;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.BadLocationException;

/**
 *
 * @author pjl
 */
public class MainPanel extends javax.swing.JPanel {

    Machine mach;
    CodeTableModel codeModel;

    /** Creates new form MainPanel */
    public MainPanel(final Machine mach) {
        this.mach=mach;
        codeModel=new CodeTableModel(mach);
        initComponents();
        codeTable.setModel(codeModel);
        mach.addObserver(new Observer(){

            public void update(Observable o, Object arg) {
                codeModel.fireTableDataChanged();
                int line=mach.getPC();
                codeTable.setRowSelectionInterval(line, line);
                codeTable.scrollRectToVisible(codeTable.getCellRect(line, line, true));
            }
            
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        editPanel = new javax.swing.JTextArea();
        stepBut = new javax.swing.JButton();
        codeTableScroll = new javax.swing.JScrollPane();
        codeTable = new javax.swing.JTable();
        loadBut = new javax.swing.JButton();
        runButton = new javax.swing.JToggleButton();
        statusPanel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        sizeText = new javax.swing.JTextField();

        editPanel.setColumns(4);
        editPanel.setRows(500);
        editPanel.setWrapStyleWord(true);
        editPanel.setAutoscrolls(true);
        jScrollPane1.setViewportView(editPanel);

        stepBut.setText("Step");
        stepBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stepActionPerformed(evt);
            }
        });

        codeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        codeTable.setEnabled(false);
        codeTableScroll.setViewportView(codeTable);

        loadBut.setText("Load");
        loadBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButActionPerformed(evt);
            }
        });

        runButton.setText("Run/Stop");
        runButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runButtonActionPerformed(evt);
            }
        });

        statusPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setText("Machine Size");

        sizeText.setText("30");
        sizeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loadBut)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(stepBut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(runButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(sizeText, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(codeTableScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(statusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 874, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, 0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(codeTableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loadBut)
                    .addComponent(stepBut)
                    .addComponent(runButton)
                    .addComponent(sizeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    private void loadButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButActionPerformed
       BufferedReader reader=new BufferedReader(new StringReader(editPanel.getText()));
        try {
            mach.load(reader);
            statusPanel.setText("LOADED OK");
        } catch (RedCodeParseException ex) {
            editPanel.setSelectionColor(Color.red);
            try {
                int i1 = editPanel.getLineStartOffset(mach.getParseLine());
                int i2= editPanel.getLineEndOffset(mach.getParseLine());
                editPanel.select(i1, i2);
            } catch (BadLocationException ex1) {
                Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex1);
            }

            statusPanel.setText("CHECK THE HIGHLIGHED LINE "+ ex.getMessage());
        }
    }//GEN-LAST:event_loadButActionPerformed

    private void stepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stepActionPerformed
        resetStatusPanel();
        try {
            mach.step();
        } catch (RedCodeParseException ex) {
            Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_stepActionPerformed

    private void runButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runButtonActionPerformed
        if (runButton.isSelected()) {
            mach.run();
        } else {
            mach.stop();
        }
    }//GEN-LAST:event_runButtonActionPerformed

    private void sizeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeTextActionPerformed
        int size=Integer.parseInt(sizeText.getText());
        mach.setSize(size);
    }//GEN-LAST:event_sizeTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable codeTable;
    private javax.swing.JScrollPane codeTableScroll;
    private javax.swing.JTextArea editPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loadBut;
    private javax.swing.JToggleButton runButton;
    private javax.swing.JTextField sizeText;
    private javax.swing.JLabel statusPanel;
    private javax.swing.JButton stepBut;
    // End of variables declaration//GEN-END:variables

    private void resetStatusPanel() {
  //      statusPanel.setText("");
    }

}
