/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WaveApplet.java
 *
 * Created on 17-Nov-2009, 10:13:10
 */
/**
 *
 * @author pjl
 */
public class WaveApplet extends javax.swing.JApplet {

    private WaveEq waveEq;

    /** Initializes the applet WaveApplet */
    public void init() {
        waveEq = new WaveEq();
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {

                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wavepanel = wavepanel=new WavePanel(waveEq);
        stepBut = new javax.swing.JButton();

        javax.swing.GroupLayout wavepanelLayout = new javax.swing.GroupLayout(wavepanel);
        wavepanel.setLayout(wavepanelLayout);
        wavepanelLayout.setHorizontalGroup(
            wavepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        wavepanelLayout.setVerticalGroup(
            wavepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 195, Short.MAX_VALUE)
        );

        stepBut.setText("STEP");
        stepBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(wavepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(stepBut)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stepBut)
                    .addComponent(wavepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void update(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update
        waveEq.step();
        wavepanel.repaint();
    }//GEN-LAST:event_update
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton stepBut;
    private javax.swing.JPanel wavepanel;
    // End of variables declaration//GEN-END:variables
}
